const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '../../.env') });

const Product = require('../models/Product');
const User = require('../models/User');
const bcrypt = require('bcryptjs');

const products = [

    // ─── ELECTRONICS — Phones ───────────────────────────────────────────────
    {
        title: 'Samsung Galaxy A55 5G',
        description: 'Experience blazing-fast 5G speeds with the Samsung Galaxy A55. Features a stunning 6.6" Super AMOLED display, 50MP triple camera system, and a powerful Exynos 1480 processor. 8GB RAM and 256GB storage give you room for everything. IP67 water resistance for peace of mind.',
        price: 89999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80'],
        stock: 45,
        rating: 4.5,
        numReviews: 128,
        tags: ['samsung', 'phone', 'smartphone', '5g', 'android', 'mobile'],
        discount: 18,
    },
    {
        title: 'iPhone 15 Pro Max 256GB',
        description: 'The most powerful iPhone ever. Titanium design, A17 Pro chip, 48MP main camera with 5x optical zoom. Experience the future of smartphones with ProMotion display and USB-C connectivity. Action button for instant access to your favourite tools.',
        price: 329999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80'],
        stock: 20,
        rating: 4.9,
        numReviews: 342,
        tags: ['iphone', 'apple', 'ios', 'smartphone', 'mobile', 'phone'],
        discount: 5,
    },
    {
        title: 'Xiaomi Redmi Note 13 Pro',
        description: '200MP camera, 120Hz AMOLED display, 67W fast charging. The Snapdragon 7s Gen 2 ensures smooth performance for gaming and multitasking. 5000mAh battery keeps you powered all day.',
        price: 49999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80'],
        stock: 60,
        rating: 4.3,
        numReviews: 89,
        tags: ['xiaomi', 'redmi', 'smartphone', 'android', 'mobile', 'phone'],
        discount: 20,
    },
    {
        title: 'OnePlus 12 5G 256GB',
        description: 'Snapdragon 8 Gen 3, 50MP Hasselblad triple camera, 100W SUPERVOOC charging that fills from 0 to 100% in just 26 minutes. 6.82" 2K ProXDR display with 120Hz adaptive refresh rate.',
        price: 109999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80'],
        stock: 30,
        rating: 4.6,
        numReviews: 156,
        tags: ['oneplus', 'phone', 'smartphone', '5g', 'android', 'mobile', 'hasselblad'],
        discount: 10,
    },
    {
        title: 'Google Pixel 8 Pro 128GB',
        description: 'Powered by Google Tensor G3. Best-in-class AI photography with Real Tone and Magic Eraser. 7 years of OS, security, and Pixel Drop updates. Temperature sensor, built-in VPN, and Titan M2 security chip.',
        price: 149999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&q=80'],
        stock: 25,
        rating: 4.7,
        numReviews: 210,
        tags: ['google', 'pixel', 'smartphone', 'android', 'mobile', 'phone', 'ai'],
        discount: 8,
    },

    // ─── ELECTRONICS — Laptops ──────────────────────────────────────────────
    {
        title: 'MacBook Air M3 13-inch',
        description: 'Supercharged by M3 chip. Up to 18 hours battery life. Fanless silent design. 8GB unified memory and 256GB SSD. The perfect laptop for students, creators, and professionals who need power without the weight.',
        price: 289000,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80'],
        stock: 15,
        rating: 4.9,
        numReviews: 215,
        tags: ['macbook', 'apple', 'laptop', 'notebook', 'mac', 'm3'],
        discount: 8,
    },
    {
        title: 'Dell XPS 15 Intel i7 RTX 4060',
        description: '13th Gen Intel Core i7, NVIDIA RTX 4060, 16GB DDR5 RAM, 512GB NVMe SSD. 15.6" OLED InfinityEdge display with 3.5K resolution. Perfect for video editing, 3D rendering, and high-performance work.',
        price: 249999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80'],
        stock: 12,
        rating: 4.7,
        numReviews: 167,
        tags: ['dell', 'laptop', 'xps', 'notebook', 'gaming', 'rtx'],
        discount: 12,
    },
    {
        title: 'Lenovo IdeaPad Slim 5 AMD Ryzen 7',
        description: 'Thin, light, and powerful. AMD Ryzen 7 5700U, 16GB RAM, 512GB SSD, 15.6" Full HD IPS display. Up to 10 hours battery life. USB-C charging, backlit keyboard, fingerprint reader.',
        price: 74999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80'],
        stock: 30,
        rating: 4.4,
        numReviews: 93,
        tags: ['lenovo', 'laptop', 'ideapad', 'notebook', 'amd', 'ryzen'],
        discount: 15,
    },
    {
        title: 'ASUS ROG Strix G16 Gaming Laptop',
        description: 'Dominate every game. Intel Core i9-13980HX, NVIDIA RTX 4070 8GB, 32GB DDR5 RAM, 1TB PCIe 4.0 SSD. 16" QHD 240Hz ROG Nebula Display. RGB per-key keyboard, AI noise-cancelling mic.',
        price: 319999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80'],
        stock: 10,
        rating: 4.8,
        numReviews: 134,
        tags: ['asus', 'rog', 'gaming', 'laptop', 'rtx', 'notebook', 'i9'],
        discount: 10,
    },
    {
        title: 'HP Pavilion 14 Intel Core i5',
        description: 'Everyday laptop with a premium feel. Intel Core i5-1235U, 8GB RAM, 512GB SSD, 14" FHD IPS display. HP Fast Charge, HDMI 2.0, USB-C. Slim profile at just 1.41kg.',
        price: 62999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&q=80'],
        stock: 35,
        rating: 4.3,
        numReviews: 87,
        tags: ['hp', 'pavilion', 'laptop', 'notebook', 'intel', 'i5'],
        discount: 18,
    },

    // ─── ELECTRONICS — Audio ────────────────────────────────────────────────
    {
        title: 'Sony WH-1000XM5 Wireless Headphones',
        description: 'Industry-leading noise cancellation with 8 microphones and two processors. 30-hour battery, LDAC Hi-Res audio, multipoint Bluetooth. Ultra-comfortable for long listening sessions.',
        price: 67000,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80'],
        stock: 25,
        rating: 4.8,
        numReviews: 445,
        tags: ['sony', 'headphones', 'wireless', 'noise cancelling', 'audio'],
        discount: 22,
    },
    {
        title: 'Apple AirPods Pro 2nd Generation',
        description: 'Next-level Active Noise Cancellation. Personalized Spatial Audio, Adaptive Transparency, H2 chip. Up to 30 hours total battery with case. MagSafe charging. Now with USB-C.',
        price: 54999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80'],
        stock: 35,
        rating: 4.8,
        numReviews: 389,
        tags: ['apple', 'airpods', 'earbuds', 'wireless', 'noise cancelling'],
        discount: 10,
    },
    {
        title: 'JBL Tune 770NC Wireless Earbuds',
        description: 'Pure Bass sound with Active Noise Cancelling. 44-hour total battery life, Fast Pair technology, water resistant IPX4. Comfortable fit for all-day wear. Available in 4 colours.',
        price: 14999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80'],
        stock: 55,
        rating: 4.3,
        numReviews: 178,
        tags: ['jbl', 'earbuds', 'wireless', 'noise cancelling', 'audio'],
        discount: 25,
    },
    {
        title: 'Bose QuietComfort 45 Headphones',
        description: 'Acclaimed noise cancellation in a refined, lightweight design. TriPort acoustic architecture for deep, powerful audio. 24-hour battery, USB-C charging, built-in mic for calls.',
        price: 52999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80'],
        stock: 20,
        rating: 4.7,
        numReviews: 263,
        tags: ['bose', 'headphones', 'wireless', 'noise cancelling', 'audio', 'qc45'],
        discount: 15,
    },
    {
        title: 'Marshall Emberton II Portable Speaker',
        description: 'True wireless stereo. Iconic Marshall design, 30+ hours playtime, IPX7 waterproof, Bluetooth 5.1. Stack with other Marshall speakers via True Stereo pairing for bigger sound.',
        price: 18999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80'],
        stock: 28,
        rating: 4.6,
        numReviews: 198,
        tags: ['marshall', 'speaker', 'bluetooth', 'portable', 'audio', 'wireless'],
        discount: 12,
    },

    // ─── ELECTRONICS — Gadgets ──────────────────────────────────────────────
    {
        title: 'Samsung 55" 4K QLED Smart TV',
        description: 'Quantum Dot technology delivers breathtaking color and contrast. Neural Quantum Processor 4K, HDR10+, 100% Color Volume. Alexa and Google Assistant built-in. Gaming Hub for Xbox and PlayStation streaming.',
        price: 119999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=80'],
        stock: 10,
        rating: 4.6,
        numReviews: 201,
        tags: ['samsung', 'tv', 'television', '4k', 'smart tv', 'qled'],
        discount: 20,
    },
    {
        title: 'Apple iPad Pro 12.9" M2 Wi-Fi 256GB',
        description: 'The ultimate iPad experience. M2 chip, stunning 12.9" Liquid Retina XDR display with ProMotion. Apple Pencil hover, Face ID, Thunderbolt port. Centre Stage keeps you in frame during video calls.',
        price: 199999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80'],
        stock: 18,
        rating: 4.9,
        numReviews: 287,
        tags: ['apple', 'ipad', 'tablet', 'm2', 'pro', 'ios'],
        discount: 6,
    },
    {
        title: 'Samsung Galaxy Watch 6 Classic 47mm',
        description: 'Rotating bezel meets premium health tracking. Advanced sleep coaching, body composition analysis, BioActive sensor. Wear OS powered by Samsung with Google apps. 40-hour battery life.',
        price: 54999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80'],
        stock: 22,
        rating: 4.5,
        numReviews: 143,
        tags: ['samsung', 'smartwatch', 'watch', 'wearable', 'galaxy', 'health'],
        discount: 14,
    },
    {
        title: 'Canon EOS R50 Mirrorless Camera',
        description: '24.2MP APS-C sensor, Dual Pixel CMOS AF II, 4K video recording. Compact body perfect for content creators and beginners. Subject tracking with eye detection for sharp portraits every time.',
        price: 134999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80'],
        stock: 12,
        rating: 4.7,
        numReviews: 98,
        tags: ['canon', 'camera', 'mirrorless', 'photography', 'dslr', '4k'],
        discount: 10,
    },
    {
        title: 'Anker 45W USB-C GaN Fast Charger',
        description: 'Charges MacBook, iPhone 15, iPad, and Samsung at full speed from a single plug. GaN technology runs 50% cooler than standard chargers. Foldable prongs, compact enough to travel anywhere.',
        price: 3499,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1609592806596-d4b8a63dc5a1?w=600&q=80'],
        stock: 100,
        rating: 4.6,
        numReviews: 312,
        tags: ['charger', 'usb-c', 'anker', 'fast charging', 'accessories', 'gan'],
        discount: 15,
    },
    {
        title: 'Logitech MX Master 3S Wireless Mouse',
        description: '8000 DPI precision sensor works on any surface including glass. MagSpeed electromagnetic scroll wheel, quiet clicks, Bolt USB receiver. Multi-device — switch between 3 computers seamlessly.',
        price: 12999,
        category: 'electronics',
        images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80'],
        stock: 40,
        rating: 4.8,
        numReviews: 234,
        tags: ['logitech', 'mouse', 'wireless', 'accessories', 'mx master', 'productivity'],
        discount: 12,
    },

    // ─── FASHION — Shoes ────────────────────────────────────────────────────
    {
        title: 'Nike Air Max 270 React',
        description: 'Full-length React foam and a Max Air unit create a plush, responsive ride. Engineered mesh upper for lightweight breathability. Rubber outsole pods for durable traction on any surface.',
        price: 18500,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'],
        stock: 40,
        rating: 4.6,
        numReviews: 234,
        tags: ['nike', 'shoes', 'sneakers', 'running', 'air max', 'footwear'],
        discount: 20,
    },
    {
        title: 'Adidas Ultraboost 23 Running Shoes',
        description: 'BOOST midsole returns energy with every stride. PRIMEKNIT+ upper adapts to your foot. Made with 50% Parley Ocean Plastic. Linear Energy Push system for a propulsive toe-off.',
        price: 22999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80'],
        stock: 32,
        rating: 4.7,
        numReviews: 198,
        tags: ['adidas', 'shoes', 'sneakers', 'running', 'ultraboost', 'footwear'],
        discount: 15,
    },
    {
        title: 'New Balance 990v6 Premium Sneakers',
        description: 'Made in USA with premium pigskin suede and mesh. ENCAP midsole with polyurethane rim. Dual-density collar foam for a comfortable fit. A timeless silhouette that never goes out of style.',
        price: 26999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80'],
        stock: 20,
        rating: 4.8,
        numReviews: 145,
        tags: ['new balance', 'shoes', 'sneakers', 'premium', 'footwear', 'made in usa'],
        discount: 10,
    },
    {
        title: 'Converse Chuck Taylor All Star Classic',
        description: 'The most iconic sneaker of all time. Canvas upper, rubber cap toe, and signature All Star ankle patch. OrthoLite cushioned insole for all-day comfort. Available in over 40 colours.',
        price: 7499,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1465453869711-7e174808ace9?w=600&q=80'],
        stock: 90,
        rating: 4.5,
        numReviews: 412,
        tags: ['converse', 'shoes', 'sneakers', 'chuck taylor', 'footwear', 'classic'],
        discount: 15,
    },

    // ─── FASHION — Clothing ─────────────────────────────────────────────────
    {
        title: "Men's Casual Slim Fit Chinos",
        description: 'Premium cotton-blend slim fit chinos. Versatile for office, casual outings, or semi-formal events. Slash pockets, button-through back pockets, belt loops. Machine washable, wrinkle-resistant fabric.',
        price: 3499,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80'],
        stock: 80,
        rating: 4.2,
        numReviews: 145,
        tags: ['men', 'pants', 'chinos', 'clothing', 'fashion', 'trousers'],
        discount: 30,
    },
    {
        title: "Women's Floral Maxi Dress",
        description: 'Elegant floral print maxi dress perfect for summer. Lightweight chiffon fabric, adjustable spaghetti straps, concealed back zipper. Fully lined, falls to the ankle. Ideal for garden parties or beach outings.',
        price: 4999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&q=80'],
        stock: 60,
        rating: 4.5,
        numReviews: 112,
        tags: ['women', 'dress', 'clothing', 'fashion', 'maxi', 'floral'],
        discount: 25,
    },
    {
        title: "Levi's 511 Slim Jeans",
        description: "The iconic 511 slim fit. Made with stretch denim for comfort and freedom of movement. Mid-rise waistline, slim through hip and thigh. Sits below the waist with a straight leg opening.",
        price: 6999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600&q=80'],
        stock: 70,
        rating: 4.6,
        numReviews: 312,
        tags: ['levis', 'jeans', 'denim', 'clothing', 'men', 'fashion'],
        discount: 18,
    },
    {
        title: "Men's Oversized Graphic Hoodie",
        description: 'Premium 400gsm cotton-fleece blend. Relaxed oversized fit with kangaroo pocket and adjustable drawstring hood. Ribbed cuffs and hem. Pre-shrunk to maintain shape after washing.',
        price: 3999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80'],
        stock: 75,
        rating: 4.4,
        numReviews: 189,
        tags: ['men', 'hoodie', 'sweatshirt', 'clothing', 'streetwear', 'fashion'],
        discount: 20,
    },
    {
        title: "Women's Cropped Leather Jacket",
        description: 'Genuine lambskin leather cropped biker jacket. Asymmetric front zip, multiple pockets, quilted shoulder panels. Fully lined with satin interior. Timeless piece that pairs with everything.',
        price: 15999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'],
        stock: 25,
        rating: 4.7,
        numReviews: 98,
        tags: ['women', 'jacket', 'leather', 'clothing', 'fashion', 'biker'],
        discount: 15,
    },
    {
        title: "Tommy Hilfiger Men's Classic Polo",
        description: 'Iconic Tommy Hilfiger flag logo polo. 100% premium pique cotton. Ribbed collar and cuffs, three-button placket, curved hem. A wardrobe essential that elevates any casual look.',
        price: 5499,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&q=80'],
        stock: 55,
        rating: 4.5,
        numReviews: 167,
        tags: ['tommy hilfiger', 'polo', 'men', 'shirt', 'clothing', 'fashion'],
        discount: 20,
    },
    {
        title: "Ray-Ban Aviator Classic Sunglasses",
        description: 'The original aviator. Gold metal frame, classic teardrop lens shape, G-15 glass lenses that block 85% of light. Polarized option available. Iconic since 1937 and still the standard for style.',
        price: 17999,
        category: 'fashion',
        images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80'],
        stock: 30,
        rating: 4.8,
        numReviews: 234,
        tags: ['ray-ban', 'sunglasses', 'eyewear', 'aviator', 'accessories', 'fashion'],
        discount: 10,
    },

    // ─── HOME & LIVING ───────────────────────────────────────────────────────
    {
        title: 'Premium Solid Wood Study Desk',
        description: 'Solid acacia wood study desk with built-in cable management. Spacious 120cm work surface, 3 deep drawers, adjustable shelf. Matching legs in solid rubber wood. Easy flat-pack assembly.',
        price: 28999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80'],
        stock: 18,
        rating: 4.6,
        numReviews: 76,
        tags: ['desk', 'furniture', 'home', 'office', 'wood', 'study'],
        discount: 18,
    },
    {
        title: 'Scandinavian Minimalist 3-Seater Sofa',
        description: 'Modern Scandinavian design in premium performance fabric. High-density 35D foam cushions, solid beech wood legs. Removable, machine-washable covers. Available in grey, beige, and navy.',
        price: 54999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80'],
        stock: 8,
        rating: 4.7,
        numReviews: 54,
        tags: ['sofa', 'furniture', 'home', 'living room', 'couch'],
        discount: 20,
    },
    {
        title: 'Nespresso Vertuo Next Coffee Machine',
        description: 'One-touch coffee brewing with Centrifusion extraction. Auto capsule recognition adjusts brewing parameters. Wifi and Bluetooth enabled. Makes espresso, double espresso, gran lungo, and mug sizes.',
        price: 19999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80'],
        stock: 22,
        rating: 4.8,
        numReviews: 167,
        tags: ['coffee', 'machine', 'kitchen', 'home', 'nespresso', 'appliance'],
        discount: 15,
    },
    {
        title: 'Dyson V15 Detect Cordless Vacuum',
        description: 'Laser reveals invisible dust on hard floors. Acoustic piezo sensor counts and sizes particles. 60 minutes run time, whole-machine filtration captures 99.99% of particles as small as 0.3 microns.',
        price: 89999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
        stock: 14,
        rating: 4.8,
        numReviews: 143,
        tags: ['dyson', 'vacuum', 'cleaner', 'home', 'appliance', 'cordless'],
        discount: 12,
    },
    {
        title: 'Instant Pot Duo 7-in-1 Electric Cooker',
        description: 'Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer in one. 6-quart capacity. Cooks up to 70% faster than traditional methods. 13 one-touch smart programs.',
        price: 12999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80'],
        stock: 35,
        rating: 4.7,
        numReviews: 298,
        tags: ['instant pot', 'kitchen', 'cooker', 'home', 'appliance', 'pressure cooker'],
        discount: 22,
    },
    {
        title: 'IKEA KALLAX 4x4 Shelf Unit',
        description: 'Versatile shelving unit that works as a room divider, bookcase, or TV stand. 16 cubbies accommodate books, baskets, or box inserts. Solid board construction, easy to assemble.',
        price: 22999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80'],
        stock: 20,
        rating: 4.5,
        numReviews: 189,
        tags: ['ikea', 'shelf', 'furniture', 'home', 'storage', 'kallax'],
        discount: 10,
    },
    {
        title: 'Philips Hue Smart LED Starter Kit',
        description: '3 colour-changing E27 bulbs + Bridge hub. 16 million colours, dim warm white to cool daylight. Works with Alexa, Google Home, Apple HomeKit. Set schedules, scenes, and automations.',
        price: 13999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80'],
        stock: 40,
        rating: 4.6,
        numReviews: 201,
        tags: ['philips', 'hue', 'smart home', 'lights', 'led', 'home automation'],
        discount: 18,
    },
    {
        title: 'Cuisinart 12-Cup Drip Coffee Maker',
        description: 'Brew strength control, 24-hour programmable timer, 1-4 cup setting for small batches. Brew Pause feature lets you pour a cup before brewing finishes. Thermal carafe keeps coffee hot for hours.',
        price: 8999,
        category: 'home',
        images: ['https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80'],
        stock: 30,
        rating: 4.4,
        numReviews: 134,
        tags: ['cuisinart', 'coffee', 'maker', 'kitchen', 'home', 'appliance'],
        discount: 20,
    },

    // ─── BEAUTY ─────────────────────────────────────────────────────────────
    {
        title: 'The Ordinary Niacinamide 10% + Zinc 1%',
        description: 'High-strength vitamin and mineral blemish formula. Reduces appearance of skin blemishes, congestion, and enlarged pores. Balances visible aspects of sebum activity. Suitable for all skin types.',
        price: 2499,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80'],
        stock: 100,
        rating: 4.7,
        numReviews: 523,
        tags: ['skincare', 'serum', 'beauty', 'niacinamide', 'face', 'the ordinary'],
        discount: 10,
    },
    {
        title: 'MAC Studio Fix Powder Foundation',
        description: 'Matte, full-coverage powder foundation with SPF 15. Controls oil, minimizes the look of pores. Long-wearing up to 12 hours, cruelty-free. 40+ shades for all undertones.',
        price: 6999,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1631730359575-38e4755d772b?w=600&q=80'],
        stock: 45,
        rating: 4.5,
        numReviews: 287,
        tags: ['makeup', 'foundation', 'beauty', 'mac', 'powder', 'face'],
        discount: 15,
    },
    {
        title: 'Olay Regenerist Micro-Sculpting Cream',
        description: 'Anti-aging moisturizer with Hyaluronic Acid and Amino-Peptide Complex II. Firms and plumps skin to reduce the look of fine lines in 4 weeks. Fragrance-free, dermatologist tested.',
        price: 3499,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80'],
        stock: 60,
        rating: 4.4,
        numReviews: 189,
        tags: ['skincare', 'cream', 'beauty', 'anti aging', 'moisturizer', 'olay'],
        discount: 20,
    },
    {
        title: "Charlotte Tilbury Pillow Talk Lip Kit",
        description: "Charlotte's iconic Pillow Talk shade in a complete lip kit. Includes the bestselling lip liner, lipstick, and gloss. Buildable nude-pink shade flatters every skin tone. Long-lasting colour.",
        price: 8999,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1586495777744-4e6232bf9b24?w=600&q=80'],
        stock: 40,
        rating: 4.8,
        numReviews: 312,
        tags: ['charlotte tilbury', 'lipstick', 'makeup', 'beauty', 'lip', 'pillow talk'],
        discount: 10,
    },
    {
        title: 'Fenty Beauty Pro Filt\'r Foundation',
        description: '40 shades. Soft matte longwear foundation for all-day coverage with a shine-free finish. Buildable from medium to full coverage. Oil-free, water-resistant. Dermatologist tested.',
        price: 7499,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80'],
        stock: 50,
        rating: 4.6,
        numReviews: 234,
        tags: ['fenty', 'foundation', 'makeup', 'beauty', 'rihanna', 'face'],
        discount: 15,
    },
    {
        title: 'Dyson Supersonic Hair Dryer',
        description: 'Engineered for fast drying and style. Digital motor V9 in the handle. Intelligent heat control measures temperature 40 times per second. Includes 5 magnetic attachments. Prevents extreme heat damage.',
        price: 54999,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=600&q=80'],
        stock: 18,
        rating: 4.7,
        numReviews: 167,
        tags: ['dyson', 'hair dryer', 'beauty', 'hair', 'tools', 'styling'],
        discount: 8,
    },
    {
        title: 'Cerave Moisturising Cream 454g',
        description: 'Developed with dermatologists. Contains 3 essential ceramides (1, 3, 6-II) that work with your skin, not against it. MVE delivery technology for 24-hour hydration. Fragrance-free, non-comedogenic.',
        price: 2999,
        category: 'beauty',
        images: ['https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=600&q=80'],
        stock: 120,
        rating: 4.9,
        numReviews: 687,
        tags: ['cerave', 'skincare', 'moisturizer', 'beauty', 'ceramides', 'face'],
        discount: 12,
    },

    // ─── SPORTS ─────────────────────────────────────────────────────────────
    {
        title: 'Wilson Pro Staff RF97 Tennis Racket',
        description: "Roger Federer's signature racket. 97 sq inch head size, 340g weight, 16×19 string pattern. Braided graphite construction for precision. For advanced players seeking ultimate control.",
        price: 24999,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=600&q=80'],
        stock: 14,
        rating: 4.8,
        numReviews: 67,
        tags: ['tennis', 'racket', 'sports', 'wilson', 'equipment'],
        discount: 12,
    },
    {
        title: 'Adidas Predator Elite FG Football Boots',
        description: 'Predator Zone technology for maximum swerve and control. Controlskin upper grips the ball in all conditions. Continental outsole for superior grip on natural grass.',
        price: 16999,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1511886929837-354d827aae26?w=600&q=80'],
        stock: 28,
        rating: 4.6,
        numReviews: 143,
        tags: ['adidas', 'football', 'boots', 'sports', 'soccer', 'predator'],
        discount: 20,
    },
    {
        title: 'Garmin Forerunner 265 GPS Smartwatch',
        description: 'Advanced running smartwatch with stunning AMOLED display. Running dynamics, HRV Status, training readiness, daily suggested workouts, and race time predictor. 13-day battery in smartwatch mode.',
        price: 79999,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80'],
        stock: 20,
        rating: 4.7,
        numReviews: 95,
        tags: ['garmin', 'smartwatch', 'watch', 'running', 'sports', 'fitness'],
        discount: 15,
    },
    {
        title: 'Yonex Arcsaber 11 Pro Badminton Racket',
        description: 'Used by professional players worldwide. Graphite shaft with Namd technology for powerful smashes. 88g lightweight frame, 4U grip size. Repulsion and control in every stroke.',
        price: 18999,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80'],
        stock: 22,
        rating: 4.7,
        numReviews: 78,
        tags: ['yonex', 'badminton', 'racket', 'sports', 'equipment'],
        discount: 15,
    },
    {
        title: 'Decathlon Yoga Mat 10mm Premium',
        description: 'Extra-thick 10mm NBR foam for joint support. Non-slip textured surface, carrying strap included. 183cm × 61cm. Perfect for yoga, pilates, stretching, and floor exercises. Easy wipe-clean.',
        price: 2999,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&q=80'],
        stock: 80,
        rating: 4.5,
        numReviews: 234,
        tags: ['yoga', 'mat', 'sports', 'fitness', 'exercise', 'decathlon'],
        discount: 25,
    },
    {
        title: 'Adjustable Dumbbell Set 5-25kg',
        description: 'Replace 15 sets of weights with one. Twist-lock weight selection from 5kg to 25kg in 2.5kg increments. Durable resin shell over cast iron plates. Non-slip handle with 360° rotating head.',
        price: 34999,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80'],
        stock: 15,
        rating: 4.6,
        numReviews: 145,
        tags: ['dumbbell', 'weights', 'gym', 'sports', 'fitness', 'workout'],
        discount: 20,
    },
    {
        title: 'Nike Pro Training Shorts',
        description: 'Dri-FIT technology wicks sweat to keep you dry and comfortable. 7" inseam, built-in brief, zip pocket for secure storage. Stretchy fabric that moves with you. Machine washable.',
        price: 3499,
        category: 'sports',
        images: ['https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&q=80'],
        stock: 60,
        rating: 4.4,
        numReviews: 178,
        tags: ['nike', 'shorts', 'sports', 'training', 'gym', 'fitness', 'clothing'],
        discount: 18,
    },

    // ─── BOOKS ──────────────────────────────────────────────────────────────
    {
        title: 'Atomic Habits by James Clear',
        description: 'The #1 New York Times bestseller. Discover the proven system for building good habits and breaking bad ones. Learn how tiny 1% improvements compound into remarkable results over time.',
        price: 1999,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80'],
        stock: 120,
        rating: 4.9,
        numReviews: 892,
        tags: ['book', 'self help', 'habits', 'productivity', 'james clear'],
        discount: 20,
    },
    {
        title: 'Rich Dad Poor Dad by Robert Kiyosaki',
        description: 'The #1 personal finance book of all time. What the rich teach their kids about money that the poor and middle class do not. Essential reading for building financial literacy and true wealth.',
        price: 1499,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=600&q=80'],
        stock: 150,
        rating: 4.7,
        numReviews: 1204,
        tags: ['book', 'finance', 'money', 'investment', 'kiyosaki', 'wealth'],
        discount: 15,
    },
    {
        title: 'Think and Grow Rich by Napoleon Hill',
        description: 'Legendary classic studied by millions worldwide. Distilled from 20 years of research into over 500 successful people including Andrew Carnegie, Henry Ford, and Thomas Edison. Timeless principles for success.',
        price: 1299,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1521123845560-14093637aa7d?w=600&q=80'],
        stock: 90,
        rating: 4.6,
        numReviews: 756,
        tags: ['book', 'success', 'wealth', 'mindset', 'napoleon hill'],
        discount: 10,
    },
    {
        title: 'Zero to One by Peter Thiel',
        description: 'Peter Thiel, co-founder of PayPal and Palantir, reveals the secret to building the future. A book of contrarian wisdom for entrepreneurs who want to create something genuinely new instead of competing.',
        price: 1799,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&q=80'],
        stock: 85,
        rating: 4.7,
        numReviews: 543,
        tags: ['book', 'startup', 'entrepreneurship', 'business', 'peter thiel'],
        discount: 12,
    },
    {
        title: 'The Psychology of Money by Morgan Housel',
        description: 'Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life\'s most important topics.',
        price: 1599,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80'],
        stock: 100,
        rating: 4.8,
        numReviews: 678,
        tags: ['book', 'finance', 'money', 'psychology', 'morgan housel', 'investing'],
        discount: 15,
    },
    {
        title: 'Deep Work by Cal Newport',
        description: 'Rules for focused success in a distracted world. Newport argues that the ability to perform deep work is becoming increasingly rare and increasingly valuable in our economy. Learn to cultivate this rare skill.',
        price: 1699,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80'],
        stock: 75,
        rating: 4.7,
        numReviews: 432,
        tags: ['book', 'productivity', 'focus', 'work', 'cal newport', 'self help'],
        discount: 10,
    },
    {
        title: 'Sapiens: A Brief History of Humankind',
        description: 'Yuval Noah Harari surveys the history of humankind from the Stone Age to the Silicon Age. How did our species succeed? What has made us so powerful? And are we happier than our ancestors? A landmark work.',
        price: 1999,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&q=80'],
        stock: 80,
        rating: 4.8,
        numReviews: 921,
        tags: ['book', 'history', 'science', 'harari', 'sapiens', 'non fiction'],
        discount: 18,
    },
    {
        title: 'The Alchemist by Paulo Coelho',
        description: 'A magical story about Santiago, an Andalusian shepherd boy, who yearns to travel in search of a worldly treasure. A profound and life-changing novel about following your dreams. 150 million copies sold.',
        price: 999,
        category: 'books',
        images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80'],
        stock: 200,
        rating: 4.8,
        numReviews: 1456,
        tags: ['book', 'fiction', 'novel', 'paulo coelho', 'classic', 'inspirational'],
        discount: 20,
    },
];

const connectDB = async () => {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected');
};

const seedDB = async () => {
    await connectDB();

    let seller = await User.findOne({ email: 'seller@smartshop.com' });
    if (!seller) {
        seller = await User.create({
            name: 'SmartShop Official Store',
            email: 'seller@smartshop.com',
            password: bcrypt.hashSync('seller123', 10),
            role: 'seller',
            sellerApplicationStatus: 'approved',
        });
        console.log('Created seller account');
    }

    let admin = await User.findOne({ email: 'admin@smartshop.com' });
    if (!admin) {
        await User.create({
            name: 'Admin',
            email: 'admin@smartshop.com',
            password: bcrypt.hashSync('admin123', 10),
            role: 'admin',
        });
        console.log('Created admin account: admin@smartshop.com / admin123');
    }

    await Product.deleteMany({});
    console.log('Cleared existing products');

    const productsWithSeller = products.map(p => ({ ...p, user: seller._id }));
    await Product.insertMany(productsWithSeller);
    console.log(`\nSeeded ${products.length} products across 6 categories:`);
    console.log('  Electronics: phones, laptops, audio, gadgets');
    console.log('  Fashion: shoes, clothing, accessories');
    console.log('  Home & Living: furniture, appliances, smart home');
    console.log('  Beauty: skincare, makeup, haircare');
    console.log('  Sports: equipment, fitness, clothing');
    console.log('  Books: business, self-help, fiction');

    mongoose.disconnect();
    console.log('\nDone! Database seeded successfully.');
    console.log('Admin login:  admin@smartshop.com / admin123');
    console.log('Seller login: seller@smartshop.com / seller123');
};

seedDB().catch(err => {
    console.error('Seed failed:', err);
    mongoose.disconnect();
    process.exit(1);
});
